### ISSUE TITLE
Clarify the expected values for subnet_ids 

### ISSUE THREAD

**Issue by medicinal-matt** [snowplow-devops/terraform-aws-collector-kinesis-ec2#11]
The current documentation of the subnet variable just mentions 

`variable "subnet_ids" {
  description = "The list of subnets to deploy the collector across"
  type        = list(string)
}`

To actually be able to apply this module, that needs to be at least two subnets across two different Availability Zones. Otherwise you get an error.

Also should these be private or public subnets? I still haven't figured it out. The only documentation I found about this is from [Quick start installation guide on aws](https://docs.snowplowanalytics.com/docs/open-source-quick-start/quick-start-installation-guide-on-aws/#select-which-example-you-want-to-use) where it says "You will need your own VPC with public and private subnets."

**Comment by jbeemster** [comment]
Hey @medicinal-matt - you are right we should be more explicit saying it needs to be > 1 subnet - we can update that.

> Also should these be private or public subnets? I still haven't figured it out

That's sort of up to you!  If you want to use Private Subnets you can, if you want to use Public Subnets you can.  The main caveat being that if you use Public Subnets you need to ensure that `associate_public_ip_address` is set to `true` otherwise you will need to be able to connect to the internet and the box will fail to bootstrap.

Networking is purposefully left vague as it really depends on your own internal requirements for deploying systems.

**Comment by medicinal-matt** [comment]
I created a pull request https://github.com/snowplow-devops/terraform-aws-collector-kinesis-ec2/pull/14

**Comment by medicinal-matt** [comment]
Maybe this is not customer support, but how can the documentation say "You will need your own VPC with public **and** private subnets", but you're now saying that I could go with either. I also thought a public subnet was required to enable clients to send events to the collector over the internet?

**Comment by jbeemster** [comment]
I think the confusion is coming from using only Private subnets - which is not possible.

For any internet facing services (like Load Balancers) you will need Public subnets but all of your application servers can be deployed into private subnet's.  Which is why the docs say that by default we only use Public but for more of a security focus you will need to use Public and Private which essentially means better protecting the services that _can_ be deployed into private subnets.

**Comment by medicinal-matt** [comment]
Thanks! Then it is public subnets we need. 

Since load balancers [are required](https://registry.terraform.io/modules/snowplow-devops/collector-kinesis-ec2/aws/latest?tab=inputs), the subnets implicitly need to be public to use this Terraform module?

**Comment by jbeemster** [comment]
It would probably help you a lot to read the example code that the documentation references and is built around.

https://github.com/snowplow/quickstart-examples/blob/main/terraform/aws/pipeline/secure/main.tf#L74
https://github.com/snowplow/quickstart-examples/blob/main/terraform/aws/pipeline/secure/main.tf#L89

The Load Balancer uses Public subnets - it needs to be addressable from the internet.
The Collector Servers use Private subnets - they do not need to be addressable directly from the internet.

> Since load balancers are required, the subnets implicitly need to be public to use this Terraform module?

So no it is not implicitly public or private for this specific module as it depends!  It is implicitly public only for  the Load Balancer module if you wanted to get pedantic about it but here it can be either according to your network setup and security requirements.

**Comment by medicinal-matt** [comment]
That quickstart example helps a lot. Since the module documentation only mentions `subnet_ids` as a single variable, I thought it needed to be the same subnet to work. Having them separated to a private and public part explains everything.
